services:
  - type: web
    name: retrolens-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_PROJECT_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: BACKEND_CORS_ORIGINS
        value: "http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:4173,http://127.0.0.1:3000,http://127.0.0.1:5173,https://retrolens.com,https://www.retrolens.com"
      - key: DEBUG
        value: "False"
      - key: CLERK_DOMAIN
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_AUDIENCE
        sync: false
    healthCheckPath: /health
    autoDeploy: false
